<?php
$privateKeyStr = @file_get_contents('keys/private.key');
if (!$privateKeyStr) {
    die("Chave privada não encontrada. Por favor, gere as chaves primeiro.");
}
?>
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Painel do Fabricante - TCC Medicamentos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://unpkg.com/openpgp/dist/openpgp.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
    <style>
        body { background-color: #f8f9fa; }
        .card { border-radius: 15px; border: none; }
        .qr-container { display: flex; justify-content: center; align-items: center; padding: 20px; background: white; border-radius: 10px; margin-top: 20px;}
    </style>
</head>
<body>
    <nav class="navbar navbar-dark bg-primary shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="index.php">⬅ Voltar ao Início</a>
            <span class="navbar-text text-white fw-bold">Módulo do Fabricante (Área Segura)</span>
        </div>
    </nav>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-header bg-dark text-white p-3">
                        <h5 class="mb-0">Cadastrar Lote de Medicamento</h5>
                    </div>
                    <div class="card-body p-4">
                        <form id="medicamentoForm">
                            <div class="mb-3">
                                <label class="form-label">Nome do Medicamento</label>
                                <input type="text" class="form-control" id="nome" required placeholder="Ex: Omeprazol 20mg">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Número do Lote</label>
                                <input type="text" class="form-control" id="lote" required placeholder="Ex: LOTE-8902A">
                            </div>
                            <button type="submit" class="btn btn-primary w-100 btn-lg mt-3" id="btn-gerar">
                                Gerar e Assinar Medicamento (PGP)
                            </button>
                        </form>

                        <div id="status" class="mt-4"></div>

                        <div id="resultado" style="display:none;" class="mt-4 text-center">
                            <h5>QR Code Seguro Gerado:</h5>
                            <div class="qr-container shadow-sm">
                                <div id="qrcode"></div>
                            </div>
                            <p class="text-muted mt-2 small">Este QR Code contém o ID único e a Assinatura PGP do laboratório.</p>
                            <button class="btn btn-outline-secondary btn-sm" onclick="location.reload()">Gerar Novo Medicamento</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Injecting private key securely (in a real scenario, this would be locked in a HSM or strictly backend) -->
    <script>
        const PRIVATE_KEY_ARMORED = `<?php echo $privateKeyStr; ?>`;

        // Generate UUID (v4)
        function generateUUID() {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }

        document.getElementById('medicamentoForm').addEventListener('submit', async (e) => {
            e.preventDefault();
            const btn = document.getElementById('btn-gerar');
            const status = document.getElementById('status');
            
            const nome = document.getElementById('nome').value;
            const lote = document.getElementById('lote').value;
            const id = generateUUID();

            btn.disabled = true;
            btn.innerText = 'Assinando digitalmente...';
            status.innerHTML = '';

            try {
                // 1. Read Private Key
                const privateKey = await openpgp.readPrivateKey({ armoredKey: PRIVATE_KEY_ARMORED });

                // 2. Data to sign: ID
                // The signature guarantees the ID was generated by the lab.
                const message = await openpgp.createMessage({ text: id });

                // 3. Sign the message
                const signature = await openpgp.sign({
                    message: message,
                    signingKeys: privateKey,
                    detached: true
                });

                // 4. Send to backend to store
                const response = await fetch('api/salvar_medicamento.php', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ id, nome, lote, assinatura: signature })
                });

                const result = await response.json();

                if (result.success) {
                    status.innerHTML = `<div class="alert alert-success">${result.message}</div>`;
                    
                    // 5. Generate QR Code with JSON containing ID and Signature
                    const qrData = JSON.stringify({ id: id, sig: signature });
                    
                    document.getElementById('resultado').style.display = 'block';
                    document.getElementById('medicamentoForm').style.display = 'none';
                    
                    new QRCode(document.getElementById("qrcode"), {
                        text: qrData,
                        width: 256,
                        height: 256,
                        colorDark : "#000000",
                        colorLight : "#ffffff",
                        correctLevel : QRCode.CorrectLevel.L
                    });

                } else {
                    status.innerHTML = `<div class="alert alert-danger">${result.message}</div>`;
                    btn.disabled = false;
                    btn.innerText = 'Tentar Novamente';
                }
            } catch (err) {
                console.error(err);
                status.innerHTML = `<div class="alert alert-danger">Erro criptográfico: ${err.message}</div>`;
                btn.disabled = false;
                btn.innerText = 'Tentar Novamente';
            }
        });
    </script>
</body>
</html>
